services:
  - type: web
    name: brightcart-backend
    runtime: java
    rootDir: brightcart-main/backend
    buildCommand: "chmod +x mvnw && ./mvnw clean package -DskipTests"
    startCommand: "java -Dspring.profiles.active=local -jar target/ecommerce-backend-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: PORT
        value: "8080"
      - key: APP_CORS_FRONTEND_URL
        sync: false
