package com.ecommerce.backend.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Profile("oracle")
public class OrderSchemaMigrationRunner implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(OrderSchemaMigrationRunner.class);

    private final JdbcTemplate jdbcTemplate;

    public OrderSchemaMigrationRunner(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(ApplicationArguments args) {
        ensureCouponsTable();
        ensureColumn("PLACED_AT", "ALTER TABLE orders ADD (placed_at TIMESTAMP)");
        ensureColumn("PROCESSING_AT", "ALTER TABLE orders ADD (processing_at TIMESTAMP)");
        ensureColumn("SHIPPED_AT", "ALTER TABLE orders ADD (shipped_at TIMESTAMP)");
        ensureColumn("DELIVERED_AT", "ALTER TABLE orders ADD (delivered_at TIMESTAMP)");
        ensureColumn("CANCELLED_AT", "ALTER TABLE orders ADD (cancelled_at TIMESTAMP)");
        ensureColumn("COUPON_CODE", "ALTER TABLE orders ADD (coupon_code VARCHAR2(80))");
        ensureColumn("DISCOUNT_AMOUNT", "ALTER TABLE orders ADD (discount_amount NUMBER(10) DEFAULT 0 NOT NULL)");

        jdbcTemplate.update(
                "UPDATE orders SET placed_at = COALESCE(placed_at, created_at) WHERE placed_at IS NULL"
        );
        jdbcTemplate.update(
                "UPDATE orders SET processing_at = COALESCE(processing_at, created_at) "
                        + "WHERE order_status IN ('PROCESSING', 'SHIPPED', 'DELIVERED') AND processing_at IS NULL"
        );
        jdbcTemplate.update(
                "UPDATE orders SET shipped_at = COALESCE(shipped_at, created_at) "
                        + "WHERE order_status IN ('SHIPPED', 'DELIVERED') AND shipped_at IS NULL"
        );
        jdbcTemplate.update(
                "UPDATE orders SET delivered_at = COALESCE(delivered_at, created_at) "
                        + "WHERE order_status = 'DELIVERED' AND delivered_at IS NULL"
        );
        jdbcTemplate.update(
                "UPDATE orders SET cancelled_at = COALESCE(cancelled_at, created_at) "
                        + "WHERE order_status = 'CANCELLED' AND cancelled_at IS NULL"
        );

        log.info("Order schema compatibility checks completed");
    }

    private void ensureCouponsTable() {
        Integer tableCount = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM user_tables WHERE table_name = 'COUPONS'",
                Integer.class
        );

        if (tableCount != null && tableCount == 0) {
            jdbcTemplate.execute("""
                    CREATE TABLE coupons (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code VARCHAR2(80) NOT NULL UNIQUE,
                        description VARCHAR2(255) NOT NULL,
                        discount_type VARCHAR2(30) NOT NULL,
                        discount_value NUMBER(10) NOT NULL,
                        min_order_amount NUMBER(10) DEFAULT 0 NOT NULL,
                        is_active NUMBER(1) DEFAULT 1 NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                    )
                    """);
            log.info("Added missing coupons table");
        }
    }

    private void ensureColumn(String columnName, String alterSql) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM user_tab_columns WHERE table_name = 'ORDERS' AND column_name = ?",
                Integer.class,
                columnName
        );

        if (count != null && count == 0) {
            jdbcTemplate.execute(alterSql);
            log.info("Added missing orders.{} column", columnName.toLowerCase());
        }
    }
}
