DECLARE
    table_count NUMBER;
    column_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO table_count
    FROM user_tables
    WHERE table_name = 'COUPONS';

    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE coupons (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code VARCHAR2(80) NOT NULL UNIQUE,
                description VARCHAR2(255) NOT NULL,
                discount_type VARCHAR2(30) NOT NULL,
                discount_value NUMBER(10) NOT NULL,
                min_order_amount NUMBER(10) DEFAULT 0 NOT NULL,
                is_active NUMBER(1) DEFAULT 1 NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            )';
    END IF;

    SELECT COUNT(*)
    INTO column_count
    FROM user_tab_columns
    WHERE table_name = 'ORDERS'
      AND column_name = 'COUPON_CODE';

    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE orders ADD (coupon_code VARCHAR2(80))';
    END IF;

    SELECT COUNT(*)
    INTO column_count
    FROM user_tab_columns
    WHERE table_name = 'ORDERS'
      AND column_name = 'DISCOUNT_AMOUNT';

    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE orders ADD (discount_amount NUMBER(10) DEFAULT 0 NOT NULL)';
    END IF;

    EXECUTE IMMEDIATE q'[
        INSERT INTO coupons (code, description, discount_type, discount_value, min_order_amount, is_active)
        SELECT 'WELCOME10', '10% off on your first order', 'PERCENTAGE', 10, 2000, 1
        FROM dual
        WHERE NOT EXISTS (SELECT 1 FROM coupons WHERE code = 'WELCOME10')
    ]';

    EXECUTE IMMEDIATE q'[
        INSERT INTO coupons (code, description, discount_type, discount_value, min_order_amount, is_active)
        SELECT 'SAVE500', 'Flat Rs. 500 off on larger baskets', 'FIXED', 500, 5000, 1
        FROM dual
        WHERE NOT EXISTS (SELECT 1 FROM coupons WHERE code = 'SAVE500')
    ]';

    EXECUTE IMMEDIATE q'[
        INSERT INTO coupons (code, description, discount_type, discount_value, min_order_amount, is_active)
        SELECT 'SHIP99', 'Shipping covered on eligible orders', 'FIXED', 99, 1500, 1
        FROM dual
        WHERE NOT EXISTS (SELECT 1 FROM coupons WHERE code = 'SHIP99')
    ]';
END;
/
